### ISSUE TITLE
How do I use meteor-froala with CFS?

### ISSUE THREAD

**Issue by jaredtmartin** [froala/meteor-froala#10]
It seems it should be rather easy, but I have no idea where to start.

**Comment by gibex** [comment]
What are you trying to do with CFS?

**Comment by jaredtmartin** [comment]
Store the images.

**Comment by gibex** [comment]
Check froala.events page
https://www.froala.com/wysiwyg-editor/docs/events#afterUploadPastedImage
https://www.froala.com/wysiwyg-editor/docs/events#fileUploaded

Shouldn't be so hard to do it.

**Comment by gibex** [comment]
I hope you do know that "CFS is under active development right now (2015-03-01)".

**Comment by jaredtmartin** [comment]
In the end I just made my own WYSIWYG editor from scratch.

**Comment by gaethug** [comment]
Check it out. 
https://www.codetutorial.io/meteor-server-file-upload/
