### ISSUE TITLE
How to use in meteor?

### ISSUE THREAD

**Issue by chenkaiC4** [froala/meteor-froala#12]
because no demo here, so i try like this,  but not work.

In `home` template

```
<template name="home">
  {{#if currentUser}}
    <p>Welcome
      {{currentUser.username}} ^_^
    </p>
  {{/if}}
  <div id="edit"></div>
</template>
```

I think, after template `home` has been rendered, should run init function, like following:

```
Template.home.onRendered(function() {
  $('div#edit').editable({
      inlineMode: false
    });
})
```

however, I get nothing.

Please give a demo to show how to use it, thanks~!

**Comment by rjsmith** [comment]
Hi,

You might want to try the https://github.com/froala/froala-reactive package, which gives a Meteor - friendly reactive wrapper around the Froala Editor plugin.  The README has some examples of how to include the template into your own Blaze templates.

**Comment by chenkaiC4** [comment]
@rjsmith thanks, i'll have a try

i found just now:
 `meteor add froala:editor` don't do what it should do, for directory `packages/froala_editor.js` is not exist.
my meteor version is **1.1**.

**Comment by gibex** [comment]
3rd party packages are stored under .meteor/
In packages/ you store your own packages.

**Comment by anuragnagarkota** [comment]
Hello

I am using meteor version METEOR@1.4.1.2
 I am trying to add the package using command meteor add froala:editor@2.6.1 but the command stucks forever. Please guide.
