### ISSUE TITLE
Question: Any plans to update this to Froala V2?

### ISSUE THREAD

**Issue by adamgins** [froala/meteor-froala#15]
HI, I just noticed this https://www.froala.com/wysiwyg-editor/v2.0/docs/migrate-from-v1 any plans to update Froala for Meteor to v2?

**Comment by rjsmith** [comment]
+1
I'd be happy to look at updating froala-reactive once this package has been updated to v2

**Comment by adamgins** [comment]
@stefanneculai how goes? Any plans to update this package to the latest Froala?

**Comment by stefanneculai** [comment]
Updated.

**Comment by adamgins** [comment]
@stefanneculai thanks heaps
