### ISSUE TITLE
How to support mutiple languages?

### ISSUE THREAD

**Issue by fbl1991** [froala/meteor-froala#17]
Now froala is only support english, according to issue #2 . But there are always some customers need it translated into other languages. How can  I make it?

**Comment by MeKarina** [comment]
+1 
difference is beautiful....

**Comment by stefanneculai** [comment]
You could download the languages separately and include them https://github.com/froala/wysiwyg-editor/tree/master/js/languages

**Comment by MeKarina** [comment]
worked! you could close this,,
thank You..

**Comment by gmacherey** [comment]
Hi guys, more than two years later I have the same problem and I can't make it work. Can someone explain how to add additionnal languages to the meteor-froala package ? Where should I put the file, and how to include it ?

Thanks in advance for your help !

**Comment by stefanneculai** [comment]
@gmacherey you should include the languages JS files just like the editor ones and then make sure you change the language param when initializing the editor.
