### ISSUE TITLE
Version 1 or 2?

### ISSUE THREAD

**Issue by MeKarina** [froala/meteor-froala#18]
Is this version 1 or 2?

packages.js state that this is version 2, but when I use v2 docs, I can't get working. It's working when I implement v1 docs

thank You

**Comment by brianmcdonough** [comment]
+1 It appears that the jquery references v1, but would be good to hear from the maintainer

**Comment by sandman18** [comment]
+1 
$(...).froalaEditor(). Is not working.

**Comment by stefanneculai** [comment]
The current version is using V2 RC3. There will be an update in the following days to V2 production ready.
