### ISSUE TITLE
Cannot update to Froala 2.0.1 on Windows 10

### ISSUE THREAD

**Issue by rufusthecat** [froala/meteor-froala#19]
Hi
I have this error when trying to update to Froala 2.01. (tried updating from 1.2.8), removed package and then add Froala 2.x and always getting this error

Error: ENOENT, open 'C:\Users\romain\AppData\Local\Temp\mt-owm4dd\web.browser\froala:editor\css\froala_editor.min.css'

Event went about remove my project completely and reinstalling from Git and still getting the same error.
My coworkers were able to update on the Linux box on the exact same project.

Thanks for helping

**Comment by EvilJohnny** [comment]
I have exactly the same problem, adding it from scratch in a clean meteor project :disappointed:

**Comment by stefanneculai** [comment]
@dandv do you have any idea about why this could happen? Seems to be a Windows10 problem since it's not happening on Linux.

**Comment by rufusthecat** [comment]
@EvilJohnny, tried your approach and still getting the same error (grrr)
@dandv, I have no idea why it is doing this as this is the only package that I am having problems with
I tried side loading it by copying all the files and it won't load font awesome even if integrated in the project. Will go back to my breathing exercices :-) before my laptop tries to fly

**Comment by jpgilchrist** [comment]
Any update on this, my buddy is also running into the same issue. I'm on mac and do not run into this.

**Comment by rufusthecat** [comment]
Not yet as I have been able to properly install it. I am taking this time to evaluate other solution (CK Editor and Alloy Editor build with React which is what we use on the client)

**Comment by stefanneculai** [comment]
@rufusthecat @jpgilchrist @EvilJohnny Could you try 2.0.1_1 and let me know if that is fixed?

**Comment by jpgilchrist** [comment]
I updated the project and have my colleague attempt it later this evening and I'll get back to you. Thank you for the quick reply @stefanneculai

**Comment by rufusthecat** [comment]
Just tried it and it works. Awesome

**Comment by stefanneculai** [comment]
Thanks.

**Comment by EvilJohnny** [comment]
I didn't tested it yet, I am waiting for a different bug in a different package with Meteor 1.2, to update everything at once.
Glad to see that is fixed though! Thanks @stefanneculai !!

**Comment by jpgilchrist** [comment]
I meant to respond, but it's fixed for us as well. Thanks!
