### ISSUE TITLE
Cursor disappears after hitting return 

### ISSUE THREAD

**Issue by adamgins** [froala/meteor-froala#20]
Hi, I am seeing some weirdness in my editor when I hit return.

This image is just before I hit return (see cursor):

![image](https://cloud.githubusercontent.com/assets/7233741/12602462/a75bcf74-c4fd-11e5-92f6-564a3ba20417.png)

Then I git return and the cursor disappears:

![image](https://cloud.githubusercontent.com/assets/7233741/12602472/bf1c1c2c-c4fd-11e5-9e79-994cfe0c2a0d.png)

Any ideas, pls?

**Comment by stefanneculai** [comment]
Is that with V2.0.5?

**Comment by adamgins** [comment]
Yes

**Comment by adamgins** [comment]
Thanks for the 2.1.0 update. 

I am still getting the cursor issue with that release. 

Also, I noticed I know have two tool bars...

![image](https://cloud.githubusercontent.com/assets/7233741/12734626/e0134ff8-c995-11e5-8be5-7c641fe118f9.png)

Have the init params changed?

**Comment by stefanneculai** [comment]
It's a new plugin called "Quick Insert". You can disable it if you don't want by not including the JS file for it. 

Please make a jsFiddle for the cursor issue, because we cannot replicate it.

**Comment by adamgins** [comment]
@stefanneculai  thanks. Just wondering, how do I disable it by using the Meteor packages.. do I need to clone it and disable that way?

re: jsFiddle - will this do, as it's in a Meteor app and that may be messing with it ? 

if you give me an email address I can give you edit rights to this buzz or you can create a new one and add a text field to it. Sorry you won't be able to see the editor unless you login to Buzzy.

https://debug.buzzy.buzz/go/2277daa9a66adb5b43cd3d74/#1a478f60240dbc5c2c5a27bd

**Comment by adamgins** [comment]
@stefanneculai I found the issue. We had a workaround that I think covered up a previous bug the the build that must have been fixed. Removing the workaround (below) fixes the issue:

```
// Marker takes up room - force it to hide
.fr-marker {
	display: block !important;
	//border: 1px solid red !important; //testing
	width: 0px !important;
	height: 0px !important;	
}
```
