### ISSUE TITLE
FroalaEditor undefined

### ISSUE THREAD

**Issue by NanIsNotANum** [froala/meteor-froala#21]
Hallo, below is my code for generating S3Hash for "  imageUploadToS3" property. (server side code)
However, it has error that FroalaEditor is not found(or undefined)....

I wonder if I should "import" froala?
if so, could you teach me how? (I though if I add by atmosphere package, I dont need to explicitly import again...)

Thanks

//------------------------------------------------------------------------------------------------------
getFroalaS3Hash:function(){
    const AMAZON_S3 = Meteor.settings.S3;

```
let configs = {
// The name of your bucket.
bucket: AMAZON_S3.bucketName,
// S3 region. If you are using the default us-east-1, it this can be ignored.
region: AMAZON_S3.region,
// The folder where to upload the images.
keyStart: 'uploads',
// File access.
acl: 'public-read',
// AWS keys.
accessKey: AMAZON_S3.AWSAccessKeyId,
secretKey: AMAZON_S3.AWSSecretAccessKey
```

  }
    console.log(configs);
    var s3Hash = FroalaEditor.S3.getHash(configs);
    return s3Hash;
  }

**Comment by stefanneculai** [comment]
Please make sure that you include it from the Node SDK: https://www.froala.com/wysiwyg-editor/docs/sdks/nodejs.
