### ISSUE TITLE
Upload with CollectionFS

### ISSUE THREAD

**Issue by datdevdave** [froala/meteor-froala#22]
Many Meteor apps use CollectionFS for file management.  Can Froala upload with this?

Love this editor.  Will use is for all my apps if I don't have to use two different file management systems.

**Comment by stefanneculai** [comment]
We don't have a built-in feature for uploading using CollectionFS. I would recommend using the default upload flow and update it as per your needs: https://www.froala.com/wysiwyg-editor/docs/concepts/image/upload
