### ISSUE TITLE
Link editing doesn't work in latest Bootstrap modal context

### ISSUE THREAD

**Issue by adcooley** [froala/meteor-froala#24]
When rendering the Froala editor inside a Bootstrap modal, link click-handling events are ignored inside the text editor.

I've created a repo that reproduces the issue, with a README explaining the issue and how to reproduce it.

https://github.com/adcooley/froala-modal-bug-repro/blob/master/README.md

**Comment by stefanneculai** [comment]
To fix it, pass `zIndex: 3000` when initializing the editor.
