### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by uzumaxy** [froala/meteor-froala#3]
Add examples of usage Froala Editor as a Meteor package.

**Comment by lionellei** [comment]
Hello, newbie question here. Is it Ok to put the S3 accesskey in client code? Or is the accesskey meant to be public?

**Comment by stefanneculai** [comment]
@lionellei Yes, it is perfectly fine to put the AccessKey in client code, this is how Amazon says to do it. https://github.com/froala/wysiwyg-editor/issues/404#issuecomment-70906962 explains how to generate the policy and signature string and then initialize the editor with those.

@uzumaxy We'll close this issue and we'll open new ones for each example if it is necessary.

**Comment by lionellei** [comment]
Thanks!

**Comment by aligajani** [comment]
I am getting this:

 XMLHttpRequest cannot load https://cft-forum.s3.amazonaws.com/. The request was redirected to 'https://cft-forum.s3-us-west-2.amazonaws.com/', which is disallowed for cross-origin requests that require preflight.

**Comment by stefanneculai** [comment]
That's because the region for your bucket is `s3-us-west-2`.

Also, you have to set the CORS on AWS like this https://gist.github.com/stefanneculai/deed108fad534d0db3ff#file-cors-file
