### ISSUE TITLE
SpellChecker: Your subscription to the service has expired. Contact support@webspellchecker.net to learn how to resume your subscription.

### ISSUE THREAD

**Issue by RegisHubelia** [froala/meteor-froala#35]
The spellchecker is loaded automatically it would seem.  I've come across other Forum where people were experiencing the same issue using the meteor package. It would seem that the spell_checker.min.js is automatically loaded, and if you do not have a subscription, you get the warning message in the console "Your subscription to the service has expired. Contact support@webspellchecker.net to learn how to resume your subscription.".

A workaround is to explicitly declare which plugin you want to use.  Adding:

			pluginsEnabled: ['align', 'charCounter', 'codeBeautifier', 'codeView', 'colors', 'draggable', 'embedly',
				'emoticons', 'entities', 'file', 'fontAwesome', 'fontFamily', 'fontSize', 'fullscreen', 'image', 'imageTUI',
				'imageManager', 'inlineStyle', 'inlineClass', 'lineBreaker', 'lineHeight', 'link', 'lists', 'paragraphFormat',
				'paragraphStyle', 'quickInsert', 'quote', 'save', 'table', 'url', 'video', 'wordPaste'],

which are usually Froala's default fixes the warning message, if anyone comes across this issue.

**Comment by dejanmartinovic** [comment]
@RegisHubelia By default, all plugins are enabled. If you want to disable certain plugin you could achieve that by modifying the `pluginsEnabled` option:
https://froala.com/wysiwyg-editor/docs/options/#pluginsEnabled
