### ISSUE TITLE
Where's best practice for including the Activation code?

### ISSUE THREAD

**Issue by adamgins** [froala/meteor-froala#9]
I with this package where do i do???? just add into any client file???

```
  $.Editable.DEFAULTS.key = 'ACTIVATION_KEY';
```

**Comment by stefanneculai** [comment]
You can pass it as an option when you initialize the editor `$(your_selector).editable({key: 'ACTIVATION_KEY'})`.

**Comment by adamgins** [comment]
@stefanneculai  thanks for quick reply Mmm.. so I don't really initialize it as I am using https://github.com/froala/froala-reactive 

I see this error:

![image](https://cloud.githubusercontent.com/assets/7233741/5947743/a6e61f32-a793-11e4-8a8b-f4af13b10289.png)



I only see this error in my Cordova app when running on my local dev machine (which would use a different domain)... I don't see it when I using the Cordova app on my live server. 

@rjsmith not sure if you have any input?

**Comment by stefanneculai** [comment]
https://github.com/froala/froala-reactive#options-and-events shows how to pass options. You'd have to do like this:
```js
{{> froalaReactive ... language=getActivationKey...}}
Template.myTemplate.helpers({
  getActivationKey: function () {
    return 'ACTIVATION_KEY';
  }
})
```

The `Unlicensed Froala Editor` message is set not to appear on localhost, that's why you don't see the message locally.

**Comment by adamgins** [comment]
Thanks. 
So I have purchased a Froala license but I need to run it on my development servers that have a different  domain.

For example, my development server may be running my dev environment/IDEO on nitrous.io or if I am testing a mobile app on an actual iOS device with excode I need to run meteor with the `--mobile-server` settings for the specific IP address. To test this with Google OAuth I need to have an actual IP - eg somename.noip.com will point to an internal address like 192.168.0.something. 

So I really need to test Froala both on desktop browsers accessing these servers or on mobile devices. Is there a way to do that, pls?

**Comment by stefanneculai** [comment]
You'd have to generate a different key for the IP you're using on the mobile device and use that key when you're testing there. I have just emailed you more details.

**Comment by jackszd** [comment]
how to add the one domain license key in Jquery program.
